version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "8080:80"
    environment:
      AUTH_TYPE: Basic
      USERNAME: admin
      PASSWORD: password
      ANONYMOUS_METHODS: ALL
